apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-container-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newjobportal
  template:
    metadata:
      name: jobportal-pod
      labels:
        app: newjobportal
    spec:
      containers:
        - name: jobportal-container
          image: sumitchavan0110/newjobportalimage:latest
          ports:
            - containerPort: 8000
